### ISSUE TITLE
Text antialiasing

### ISSUE THREAD

**Issue by v0dro** [SciRuby/rubyplot#23]
A weird problem happens when calling `Figure#write` twice on the same graph. For the first time, all the text on the Figure is antialiased however the second time, the text appears fuzzy and is probably not so.

Here is the image of the first time:
![plots_stacked_bar_in_a_small_size](https://user-images.githubusercontent.com/2629909/50499090-0492b980-0a8a-11e9-8d5b-b68124f5d883.png)

And this is the second time:
![plots_stacked_bar_in_a_small_size](https://user-images.githubusercontent.com/2629909/50499093-0f4d4e80-0a8a-11e9-9a02-13fd8a3e75ba.png)

You can reproduce this issue by running any test in the rspec and comparing both images.

**Comment by v0dro** [comment]
@arzoo14 this might be a good opportunity for you to understand image magick.

**Comment by arzoo14** [comment]
@v0dro I read about rmagick. I am not able to plot graphs. When I am running rspec command like 
`rspec spec/scripting_layer/single_plot_graph_spec.rb:17` 

It is giving 
```
Failures:

  1) Rubyplot::SPI#line creates a simple line graph
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: a.line! @x1, @y1
          
          NoMethodError:
            undefined method `line!' for #<Rubyplot::SPI:0x0000000001c49720>
          # ./spec/scripting_layer/single_plot_graph_spec.rb:20:in `block (3 levels) in <top (required)>'

     1.2) Failure/Error: File.delete 'spec/reference_images/file_name.bmp'
          
          Errno::ENOENT:
            No such file or directory @ apply2files - spec/reference_images/file_name.bmp
          # ./spec/scripting_layer/single_plot_graph_spec.rb:14:in `delete'
          # ./spec/scripting_layer/single_plot_graph_spec.rb:14:in `block (2 levels) in <top (required)>'

  2) Rubyplot::SPI#line creates a line graph with points marked
     Got 0 failures and 2 other errors:

     2.1) Failure/Error: a.line! @x1, @y1, marker_size: 1
          
          NoMethodError:
            undefined method `line!' for #<Rubyplot::SPI:0x0000000001c2ec40>
          # ./spec/scripting_layer/single_plot_graph_spec.rb:29:in `block (3 levels) in <top (required)>'

     2.2) Failure/Error: File.delete 'spec/reference_images/file_name.bmp'
          
          Errno::ENOENT:
            No such file or directory @ apply2files - spec/reference_images/file_name.bmp
          # ./spec/scripting_layer/single_plot_graph_spec.rb:14:in `delete'
          # ./spec/scripting_layer/single_plot_graph_spec.rb:14:in `block (2 levels) in <top (required)>'

  3) Rubyplot::SPI#line creates a red dashed line graph with points marked
     Got 0 failures and 2 other errors:

     3.1) Failure/Error: a.line! @x1, @y1, line_color: :red, line_type: :dashed
          
          NoMethodError:
            undefined method `line!' for #<Rubyplot::SPI:0x0000000001bafb48>
          # ./spec/scripting_layer/single_plot_graph_spec.rb:38:in `block (3 levels) in <top (required)>'

     3.2) Failure/Error: File.delete 'spec/reference_images/file_name.bmp'
          
          Errno::ENOENT:
            No such file or directory @ apply2files - spec/reference_images/file_name.bmp
          # ./spec/scripting_layer/single_plot_graph_spec.rb:14:in `delete'
          # ./spec/scripting_layer/single_plot_graph_spec.rb:14:in `block (2 levels) in <top (required)>
```
Please guide how to plot graphs so that I can start working on issues.
