### ISSUE TITLE
Plots inconsistency

### ISSUE THREAD

**Issue by arzoo14** [SciRuby/rubyplot#37]
@v0dro 
Plots are not coming appropriately as they were coming earlier. Many plots are coming in a single plot. Even my branch is with current master.
![accepts_both_x_and_y_data](https://user-images.githubusercontent.com/17689823/51413919-75fbee80-1b96-11e9-9eb9-e04b91f62fa6.png)

**Comment by v0dro** [comment]
Can you pull the latest master and try again? Exactly which file from the tests have you posted here?

In the latest master, set this [argument](https://github.com/SciRuby/rubyplot/blob/master/spec/spec_helper.rb#L11) to `:magick`, and then check the files generated in `spec/temp/`.

**Comment by arzoo14** [comment]
@v0dro 
I've pulled the latest master and after running the command `rspec`, the following error is coming : 
```
An error occurred while loading spec_helper.
Failure/Error: require_relative '../../grruby.so'
```
Last time, I have posted the results from `spec/temp/` file.

**Comment by v0dro** [comment]
Just comment out the `require_relative '../../grruby.so'` line and remove any other requires related to GR.

**Comment by arzoo14** [comment]
Done as you have said but still the following errors are coming : 
```
 1) Rubyplot::Axes b: #<Rubyplot::Backend::MagickWrapper:0x00000000030b5240>. #stacked_bar! plots multiple stacked bar graphs with default colors
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: @abs_x1 = @axes.origin[0]
          
          NoMethodError:
            undefined method `[]' for nil:NilClass
          # ./lib/rubyplot/artist/axis/x_axis.rb:8:in `initialize'
          # ./lib/rubyplot/artist/axes.rb:96:in `new'
          # ./lib/rubyplot/artist/axes.rb:96:in `initialize'
          # ./lib/rubyplot/artist/figure.rb:69:in `new'
          # ./lib/rubyplot/artist/figure.rb:69:in `add_subplot'
          # ./spec/axes_spec.rb:17:in `block (3 levels) in <top (required)>'

     1.2) Failure/Error: Rubyplot.backend.init_output_device if output
          
          NoMethodError:
            undefined method `init_output_device' for #<Rubyplot::Backend::MagickWrapper:0x00000000030b5240>
          # ./lib/rubyplot/artist/figure.rb:96:in `write'
          # ./spec/spec_helper.rb:51:in `block (2 levels) in <top (required)>'
```

These errors are coming for every plot.

**Comment by arzoo14** [comment]
@v0dro gentle ping !

**Comment by v0dro** [comment]
Ah. That's because I committed some of the GR stuff (which is not ready) into master by mistake. I can correct this by Monday evening by keeping the master stable and/or finishing the GR integration and merging GR into this.

Until then maybe you can try out a previous commit that works. Like this one: https://github.com/SciRuby/rubyplot/commit/71b99fa5e8e1f053025d6ec3a16ac126aee74e56
